<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\EliteFIPServer.Version.props" />
  <Import Project="..\EliteFIPServer.Matric.props" />

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>EliteFIPServer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EliteAPI">
      <HintPath>..\..\EliteAPI\EliteAPI\bin\Release\netstandard2.0\EliteAPI.dll</HintPath>
    </Reference>
    <Reference Include="MatricIntegration">
      <HintPath>$(MatricIntegrationPath)</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="BuildUiWhenCoreBuilds" BeforeTargets="Build" Condition="'$(IsUiBuildTriggeredFromCore)' != 'true'">
    <MSBuild Projects="..\EliteFIPServer.UI\EliteFIPServer.UI.csproj"
             Targets="Build"
             Properties="Configuration=$(Configuration);Platform=$(Platform);BuildProjectReferences=false;IsUiBuildTriggeredFromCore=true" />
  </Target>

</Project>

